from antlr4 import *
from antlr4.tree.Trees import Trees
from antlr4.tree.Tree import TerminalNodeImpl
from antlrFiles.pythonicvisitor import PythonicVisitor


if "." in __name__:
    from antlrFiles.PythonicParser import PythonicParser
else:
    from antlrFiles.PythonicParser import PythonicParser

# The RoleBuilder class is responsible to extract the defined roles based on a parse tree produced from a specification
# by the PythonicParser. The class inherits from PythonicVistor, which is auto-generated by antlr4 based on the grammar file

class Rolebuilder(PythonicVisitor):

    def __init__(self):
        self.roles: set[str] = set()

    # Visits the roles node and returns all defined roles
    def visitSpecification(self, ctx: PythonicParser.SpecificationContext) -> set[str]:
        self.visitRoles(ctx.getChild(0))
        return self.roles
    
    # Returns the role found in the context
    def visitRole(self, ctx: PythonicParser.RoleContext) -> str:
        return ctx.getChild(0).getText()

    # Determines the count of defined roles and adds each role to the set of roles
    def visitRoles(self, ctx:PythonicParser.RolesContext) -> None:
        roleCount: int = ctx.getChild(1).getChildCount() - 2
        roleNodes: range =  range(1, roleCount + 1)
        for roleNode in roleNodes:
            role: str = self.visitRole(ctx.getChild(1).getChild(roleNode))
            self.roles.add(role)

    def dump(self, node, depth=0, ruleNames=None):
        depthStr = '. ' * depth
        if isinstance(node, TerminalNodeImpl):
            print(f'{depthStr}{node.symbol}')
        else:
            print(f'{depthStr}{Trees.getNodeText(node, ruleNames)}')
            for child in node.children:
                self.dump(child, depth + 1, ruleNames)